spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require&prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: false
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        type: trace
        use_identifier_rollback: true
        connection:
          provider_disables_autocommit: true

  security:
    jwt:
      secret: your_jwt_secret_key_here_make_it_long_and_secure_at_least_256_bits
      expiration: 86400 # 24 hours in seconds

web3j:
  client-address: https://rpc-mumbai.maticvigil.com # Polygon Mumbai RPC
  network-id: 80001 # Mumbai testnet chain ID
  http-timeout-seconds: 60
  contract-gas-limit: 2100000
  contract-gas-price: 40000000000 # 40 Gwei

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: INFO
    com.carpooling: DEBUG
    org.web3j: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE 